"""empty message

Revision ID: 95edb29b6d9e
Revises: 52f67ff23341
Create Date: 2024-01-11 09:38:45.378564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95edb29b6d9e'
down_revision = '52f67ff23341'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('linkedin', 'length_of_position',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('linkedin', 'length_of_position',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
